### ISSUE TITLE
Handling of malformed data truncates string

### ISSUE THREAD

**Issue by romanofski** [dankogai/p5-encode#88] opened 2017-01-05 04:59 UTC
I wonder if the Encoding modules behaviour in terms of handling malformed data has regressed. I'm using the following single line with an invalid non-utf8 character:

    perl -MEncode -E 'say Encode::decode(qq(UTF-8), "Mu\361oz", Encode::FB_HTMLCREF)'

and expect it being returned as:

    Mu&amp;#241;oz

I've tested this on Fedora 24 with Perl 5.22 and Encode 2.84 which returns the entire string including the replaced invalid characters.

When I try decode on Fedora 25 with Perl 5.24 and Encode 2.88 I get a truncated string:

    Mu&#241;

Using not the Fedora packages, it seems the problem was introduced in 2.87, since 2.86 is still returning a non-truncated result.

Disclaimer: My Perl experience is very limited. Perhaps I've missed something important and this is expected behaviour.

**Comment by romanofski** [comment] 2017-01-05 05:30
We've just noticed, that this seems to be only happening if two extra bytes follow the invalid character like in the example. If I add more, e.g.:

    perl -MEncode -E 'say Encode::decode(qq(UTF-8), "Mu\361lololooz", Encode::FB_HTMLCREF)'

it correctly returns:

    Mu&#241;lololooz

**Comment by pali** [comment] 2017-01-13 12:23
Read documentation: https://metacpan.org/pod/Encode#FB_PERLQQ-FB_HTMLCREF-FB_XMLCREF
> When you decode, \xHH is inserted for a malformed character, where HH is the hex representation of the octet that could not be decoded to utf8. When you encode, \x{HHHH} will be inserted, where HHHH is the Unicode code point (in any number of hex digits) of the character that cannot be found in the character repertoire of the encoding.
> 
> The HTML/XML character reference modes are about the same. In place of \x{HHHH}, HTML uses &#NNN; where NNN is a decimal number, and XML uses &#xHHHH; where HHHH is the hexadecimal number.

**Comment by pali** [comment] 2017-01-13 15:19
Probably you are facing problem fixed in pull request #84. Can you try version from git master?

**Comment by romanofski** [comment] 2017-01-17 04:37
Tested it with git master (HEAD at a70d0f60d975c76d423d6a0aa26a75fee88067b9) at the problem seems to be fixed. I went back to b426e97a6d6ce789cba686917b8d73df481f8926 and ran into the problem again. I suppose the issue can be closed. Many thanks!

**Comment by pali** [comment] 2017-01-26 22:00
If you are unable to reproduce your problem anymore with last git version, then it is really fixed and you can close this bug.

**Closed** 2017-01-27 05:27 UTC
